#if UNITY_6000_5_OR_NEWER
using Unity.Scripting.LifecycleManagement;
#endif
#if UNITY_OPENXR_HAS_EXTENSIBLE_HAND_TRACKING
using System;
using System.Runtime.InteropServices;

namespace UnityEngine.XR.Hands.Tests.OpenXR.MockHandsRuntime
{
    /// <summary>
    /// Base class for implementing a native entry point that manages delegate lifetime
    /// and function pointer marshaling.
    ///
    /// Each derived class must still own a <c>[MonoPInvokeCallback]</c> static interceptor
    /// method that catches exceptions before they cross the native/managed boundary.
    /// </summary>
    /// <remarks>
    /// Uses the CRTP (Curiously Recurring Template Pattern): generic statics are
    /// per closed type, so <see cref="s_Current"/> is isolated per thunk class.
    /// The base holds and pins the delegate and computes the <see cref="IntPtr"/>,
    /// but cannot invoke the delegate — the parameter list is unknown at the
    /// generic level.
    /// </remarks>
    /// <typeparam name="TDerived">The concrete thunk type (CRTP self-type).
    /// Ensures <see cref="s_Current"/> is scoped to each derived class.</typeparam>
    /// <typeparam name="TDelegate">The delegate type matching the native function
    /// signature. Cannot be invoked generically — derived classes call
    /// <c>s_Current.mock(...)</c> with the concrete parameter list.</typeparam>
#if UNITY_6000_5_OR_NEWER
    [NoAutoStaticsCleanup]
#endif
    abstract class NativeCallbackThunk<TDerived, TDelegate>
        where TDerived : NativeCallbackThunk<TDerived, TDelegate>
        where TDelegate : Delegate
    {
        /// <summary>
        /// The active thunk instance whose <see cref="mock"/> delegate will be
        /// called by the static interceptor. Per closed generic type.
        /// </summary>
        protected static TDerived s_Current;

        // Prevents the GC from collecting the delegate object that the
        // marshaling trampoline references. The trampoline (generated by
        // Mono JIT or IL2CPP) holds an internal reference to this delegate;
        // if collected, native calls through FunctionPointer crash.
        static TDelegate s_PinnedDelegate;
        static IntPtr s_FunctionPointer;
        static bool s_Initialized;

        /// <summary>
        /// User-settable mock delegate. Tests assign this to control behavior
        /// when native code calls through <see cref="FunctionPointer"/>.
        /// </summary>
        public TDelegate mock { get; set; }

        /// <summary>
        /// Stable native function pointer for registering with
        /// <see cref="MockOpenXREnvironment.SetFunctionForInterceptor"/>.
        /// Points to a runtime-generated C-ABI trampoline, not directly
        /// to the managed interceptor method.
        /// </summary>
        public IntPtr FunctionPointer => s_FunctionPointer;

        /// <summary>
        /// Initializes the thunk. On first call per closed generic type, pins
        /// the interceptor delegate and computes the native function pointer.
        /// Subsequent instances reuse the same pointer (the static interceptor
        /// method never changes).
        /// </summary>
        /// <param name="interceptor">The static <c>[MonoPInvokeCallback]</c>
        /// method, passed as a delegate from the derived class constructor.</param>
        protected NativeCallbackThunk(TDelegate interceptor)
        {
            if (!s_Initialized)
            {
                s_PinnedDelegate = interceptor;
                s_FunctionPointer = Marshal.GetFunctionPointerForDelegate(interceptor);
                s_Initialized = true;
            }
        }

        /// <summary>
        /// Set this thunk as the active instance for its static interceptor.
        /// </summary>
        public void Activate() => s_Current = (TDerived)this;

        /// <summary>
        /// Clear this thunk as the active instance if it is current.
        /// </summary>
        public void Deactivate()
        {
            if (s_Current == (TDerived)this)
                s_Current = null;
        }
    }
}
#endif
